version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  lint:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            pip install flake8==4.0.1
            flake8 --ignore=E501,F401,E303,E402 .

  python-test:
    docker:
      - image: cimg/python:3.11
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_PASSWORD: acendasloyalty
          POSTGRES_USER: acendasloyalty
          POSTGRES_DB: acendasloyalty
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Create dummy files for compose
          command: touch .env
      - run:
          name: Run tests
          command: python manage.py test
 
workflows:
  test-and-lint:
    jobs:
      - lint
      - python-test