version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  lint:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            pip install flake8==4.0.1
            flake8 --ignore=E501,F401,E303,E402 .

  build-and-test:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Create dummy files for compose
          command: touch .env
      - run:
          name: Spin up docker-compose
          command: docker-compose up -d
      - run:
          name: Run tests
          command: python manage.py test
 
workflows:
  test-and-lint:
    jobs:
      - lint
      - build-and-test