version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  lint:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            pip install flake8==4.0.1
            flake8 --ignore=E501,F401,E303,E402 .

  build-and-test:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '3.8'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Create dummy files for compose
          command: touch .env
      - run:
          name: Spin up docker-compose
          command: docker-compose up -d
      - run:
          name: Run tests
          command: python manage.py test
 
workflows:
  test-and-lint:
    jobs:
      - lint
      - build-and-test